### ISSUE TITLE
MiBand 2 and MiBand HRX Support

### ISSUE THREAD

**Issue by Jay268** [AlexanderHryk/MiFood#1]
@AlexanderHryk It seems i found your code while doing some research for MiBand relate integration in Android. Currently as written in readme.md your code is Supporting Mi Band 1A, Mi Band 1S.

Can it be possible to add support for MiBand2 and MiBand HRX because while executing your code i am not be able to connect to ble device as my band is MiBandHRX.

I need to get Battery status , Steps , heart rate for MiBand HRX and MiBand2 so that i request you to look into this if you can add support for that too.

It will be great it you look into something gets work for it.

**Comment by AlexanderHryk** [comment]
@Jay268 Hi. Sorry, but this project was the part of my university work, so it is not supported at this time.
